
// 1)შექმენით ჯავასკრიპტის ფაილი ,დააკავშირე html ის ფაილთან,ჯს ის ფაილში console.log()ის გამოყენებით დაბეჭდეთ 10 ჯერ განსხვავებული ცხოველის სახელი,გახსენით კონსოლი და ნახეთ შედეგი
console.log('diana dzukaevi')
console.log('avto gulashvili')
console.log('girorgi gelashvili')
console.log('natela nateladze')
console.log('giorgi shukakidze')
console.log('diana sdadd')
console.log('saqlome zurabishvili')
console.log('avto nachyepia')
console.log('batoni daviti')
console.log('erea dueasvhilii')
console.log('dianea evadze')
console.log('dia enekaevishvili')
console.log('di eaevi')
console.log('diae nakeaevadze')